/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#0053db",
        "on-secondary-fixed": "#002113",
        "secondary-fixed-dim": "#4edea3",
        "primary-container": "#2563eb",
        "surface-container-low": "#eff4ff",
        "error": "#ba1a1a",
        "secondary-fixed": "#6ffbbe",
        "on-primary-container": "#eeefff",
        "error-container": "#ffdad6",
        "on-surface": "#0b1c30",
        "secondary": "#006c49",
        "primary-fixed": "#dbe1ff",
        "tertiary-container": "#00788c",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "surface": "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "outline": "#737686",
        "on-error-container": "#93000a",
        "surface-container": "#e5eeff",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed": "#00174b",
        "on-secondary-container": "#00714d",
        "tertiary": "#005e6e",
        "outline-variant": "#c3c6d7",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-container": "#d7f6ff",
        "on-tertiary-fixed-variant": "#004e5c",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed": "#001f26",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#434655",
        "tertiary-fixed": "#acedff",
        "on-error": "#ffffff",
        "background": "#f8f9ff",
        "on-background": "#0b1c30",
        "on-primary": "#ffffff",
        "inverse-surface": "#213145",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed-variant": "#003ea8",
        "primary": "#004ac6"
      },
      fontFamily: {
        "h1": ["Manrope"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "h3": ["Manrope"],
        "h2": ["Manrope"],
        "label-md": ["Inter"],
        "caption": ["Inter"],
      },
      fontSize: {
        "h1": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "h3": ["24px", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600" }],
        "h2": ["32px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "caption": ["12px", { "lineHeight": "1.2", "letterSpacing": "0", "fontWeight": "400" }],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "0.5rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "unit": "8px",
        "margin-desktop": "32px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in-down': 'fadeInDown 0.4s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-in-right': 'slideInRight 0.4s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'float': 'float 6s ease-in-out infinite',
        'progress': 'progress 1.5s ease-out forwards',
        'spin-slow': 'spin 4s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 20px rgba(124, 58, 237, 0.3)' },
          '100%': { boxShadow: '0 0 40px rgba(124, 58, 237, 0.6)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        progress: {
          '0%': { width: '0%' },
          '100%': { width: 'var(--progress-width, 100%)' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      boxShadow: {
        'glow-sm': '0 0 15px rgba(124, 58, 237, 0.3)',
        'glow-md': '0 0 30px rgba(124, 58, 237, 0.4)',
        'glow-lg': '0 0 60px rgba(124, 58, 237, 0.5)',
        'inner-glow': 'inset 0 0 20px rgba(124, 58, 237, 0.1)',
      },
    },
  },
  plugins: [],
}
